- name: "Check if Initial Borg Backup exists"
  stat:
    path: /var/backups/borg
  register: 'borgdir'

- name: "Create /var/backups/borg"
  ansible.builtin.file:
    path: /var/backups/borg
    state: directory
  when: 'not borgdir.stat.exists'

- name: "Initialize BorgBackup"
  ansible.builtin.shell:
    cmd: borg init --encryption=repokey-blake2 /var/backups/borg
  environment:
    BORG_PASSPHRASE: "{{ BORG_PASS }}"
  when: 'not borgdir.stat.exists'

- name: "Initial Backup of /{etc,var,opt,root}"
  ansible.builtin.shell:
    cmd: borg create /var/backups/borg/::{{ item }}-$(date --iso) /{{ item }}
  environment:
    BORG_PASSPHRASE: "{{ BORG_PASS }}"
  with_items:
    - etc
    - var
    - opt
    - root
  ignore_errors: yes
  when: 'not borgdir.stat.exists'
