- name: "Copy monitrc.j2 to /etc/monit/monitrc"
  ansible.builtin.template:
    src: monitrc.j2
    dest: /etc/monit/monitrc
    mode: 0700
    owner: root
    group: root

- name: "Copy monit.conf.j2 to /etc/monit/conf.d/system.service"
  ansible.builtin.template:
    src: monit.conf.j2
    dest: /etc/monit/conf.d/system.service
    mode: 0664
    owner: root
    group: root

- name: "Run Syntax Check"
  ansible.builtin.shell:
    cmd: monit -t

- name: "Restart monitd"
  ansible.builtin.systemd:
    name: monit
    state: restarted

- name: "Run Initial Monit status"
  ansible.builtin.shell:
    cmd: monit status
  register: monit_status

- name: "Print Monit Status"
  debug:
   var: monit_status.stdout
