---
- name: "Create Azure VM"
  hosts: "all"
  become: true
  collections:
    - azure.azcollection
  roles:
    - { role: setup }
- name: "Setup VM"    
  hosts: provisioning
  become: true
  roles:
    - { role: hardening }
